# Generated by Django 2.1.7 on 2019-03-23 12:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_deleted_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='todo',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
