# Generated by Django 2.2.3 on 2019-08-25 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('todo', '0003_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labels.Label'),
        ),
    ]
