# Generated by Django 2.1.7 on 2019-03-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190323_1231'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='todo',
            managers=[
            ],
        ),
    ]
